module.exports =  [{ path: '/Users/samrichard/Development/plugabilly/node_modules/ava',
    package:
     { name: 'ava',
       version: '0.10.0',
       description: 'Futuristic test runner 🚀',
       license: 'MIT',
       repository:
        { type: 'git',
          url: 'git+https://github.com/sindresorhus/ava.git' },
       homepage: 'https://ava.li',
       author:
        { name: 'Sindre Sorhus',
          email: 'sindresorhus@gmail.com',
          url: 'sindresorhus.com' },
       maintainers:
        [ { name: 'jamestalmage', email: 'james@talmage.io' },
          { name: 'kevva', email: 'kevinmartensson@gmail.com' },
          { name: 'sindresorhus', email: 'sindresorhus@gmail.com' },
          { name: 'vdemedes', email: 'vdemedes@gmail.com' } ],
       bin: { ava: 'cli.js' },
       engines: { node: '>=0.10.0' },
       scripts:
        { test: 'xo && nyc --cache --reporter=lcov --reporter=text tap --no-cov --timeout=150 test/*.js test/reporters/*.js',
          'test-win': 'tap --no-cov --reporter=classic --timeout=150 test/*.js test/reporters/*.js',
          visual: 'node test/visual/run-visual-tests.js' },
       files: [ 'lib', '*.js' ],
       keywords:
        [ 'test',
          'runner',
          'ava',
          'concurrent',
          'parallel',
          'fast',
          'tape',
          'tap',
          'mocha',
          'qunit',
          'jasmine',
          'tdd',
          'cli-app',
          'cli',
          'assert',
          'assertion',
          'futuristic',
          'promise',
          'promises',
          'async',
          'function',
          'await',
          'generator',
          'generators',
          'yield',
          'observable',
          'observables',
          'tap' ],
       dependencies: { ava: { dependencies: {} } },
       devDependencies:
        { coveralls: '^2.11.4',
          delay: '^1.3.0',
          'get-stream': '^1.1.0',
          inquirer: '^0.11.1',
          nyc: '^5.1.0',
          pify: '^2.3.0',
          rimraf: '^2.5.0',
          'signal-exit': '^2.1.2',
          sinon: '^1.17.2',
          'source-map-fixtures': '^1.0.0',
          tap: '^5.0.1',
          xo: '*',
          'zen-observable': '^0.1.6' },
       xo: { ignore: [ 'cli.js' ] },
       gitHead: '3e869956894e77256ee7672f053e2feea1166fe5',
       bugs: { url: 'https://github.com/sindresorhus/ava/issues' },
       _id: 'ava@0.10.0',
       _shasum: '0ae47b47cf77c51afd3bb35d41b70bbd79bc8c20',
       _from: 'ava@>=0.10.0 <0.11.0',
       _npmVersion: '3.5.3',
       _nodeVersion: '5.3.0',
       _npmUser: { name: 'jamestalmage', email: 'james@talmage.io' },
       dist:
        { shasum: '0ae47b47cf77c51afd3bb35d41b70bbd79bc8c20',
          tarball: 'http://registry.npmjs.org/ava/-/ava-0.10.0.tgz' },
       directories: {},
       _resolved: 'https://registry.npmjs.org/ava/-/ava-0.10.0.tgz',
       readme: 'ERROR: No README data found!',
       realName: 'ava',
       _dependencies:
        { 'arr-flatten': '^1.0.1',
          arrify: '^1.0.0',
          'ava-init': '^0.1.0',
          'babel-core': '^6.3.21',
          'babel-plugin-espower': '^2.1.0',
          'babel-plugin-transform-regenerator': '6.3.26',
          'babel-plugin-transform-runtime': '^6.3.13',
          'babel-preset-es2015': '^6.3.13',
          'babel-preset-stage-2': '^6.3.13',
          'babel-runtime': '^6.3.19',
          bluebird: '^3.0.0',
          'caching-transform': '^1.0.0',
          chalk: '^1.0.0',
          'cli-cursor': '^1.0.2',
          'co-with-promise': '^4.6.0',
          commondir: '^1.0.1',
          'convert-source-map': '^1.1.2',
          'core-assert': '^0.1.0',
          debug: '^2.2.0',
          deeper: '^2.1.0',
          'empower-core': '^0.4.0',
          figures: '^1.4.0',
          'find-cache-dir': '^0.1.1',
          'fn-name': '^2.0.0',
          globby: '^4.0.0',
          'is-generator-fn': '^1.0.0',
          'is-observable': '^0.1.0',
          'is-promise': '^2.1.0',
          'last-line-stream': '^1.0.0',
          'loud-rejection': '^1.2.0',
          'max-timeout': '^1.0.0',
          'md5-hex': '^1.2.0',
          meow: '^3.7.0',
          'object-assign': '^4.0.1',
          'observable-to-promise': '^0.1.0',
          'pkg-conf': '^1.0.1',
          plur: '^2.0.0',
          'power-assert-formatter': '^1.3.0',
          'power-assert-renderers': '^0.1.0',
          'pretty-ms': '^2.0.0',
          'require-precompiled': '^0.1.0',
          'resolve-cwd': '^1.0.0',
          'serialize-error': '^1.1.0',
          'set-immediate-shim': '^1.0.1',
          'source-map-support': '^0.4.0',
          'stack-utils': '^0.3.0',
          'strip-bom': '^2.0.0',
          'time-require': '^0.1.2',
          'unique-temp-dir': '^1.0.0',
          'update-notifier': '^0.6.0' },
       extraneous: false,
       path: '/Users/samrichard/Development/plugabilly/node_modules/ava',
       realPath: '/Users/samrichard/Development/plugabilly/node_modules/ava',
       parent: '[Circular]',
       depth: 1,
       peerDependencies: {} } },
  { path: '/Users/samrichard/Development/plugabilly/node_modules/bluebird',
    package:
     { name: 'bluebird',
       description: 'Full featured Promises/A+ implementation with exceptionally good performance',
       version: '3.1.5',
       keywords:
        [ 'promise',
          'performance',
          'promises',
          'promises-a',
          'promises-aplus',
          'async',
          'await',
          'deferred',
          'deferreds',
          'future',
          'flow control',
          'dsl',
          'fluent interface' ],
       scripts:
        { lint: 'node scripts/jshint.js',
          test: 'node tools/test.js',
          istanbul: 'istanbul',
          prepublish: 'npm run generate-browser-core && npm run generate-browser-full',
          'generate-browser-full': 'node tools/build.js --no-clean --no-debug --release --browser --minify',
          'generate-browser-core': 'node tools/build.js --features=core --no-debug --release --zalgo --browser --minify && mv js/browser/bluebird.js js/browser/bluebird.core.js && mv js/browser/bluebird.min.js js/browser/bluebird.core.min.js' },
       homepage: 'https://github.com/petkaantonov/bluebird',
       repository:
        { type: 'git',
          url: 'git://github.com/petkaantonov/bluebird.git' },
       bugs: { url: 'http://github.com/petkaantonov/bluebird/issues' },
       license: 'MIT',
       author:
        { name: 'Petka Antonov',
          email: 'petka_antonov@hotmail.com',
          url: 'http://github.com/petkaantonov/' },
       devDependencies:
        { acorn: '~0.6.0',
          baconjs: '^0.7.43',
          bluebird: '^2.9.2',
          'body-parser': '^1.10.2',
          browserify: '^8.1.1',
          'cli-table': '~0.3.1',
          co: '^4.2.0',
          'cross-spawn': '^0.2.3',
          glob: '^4.3.2',
          'grunt-saucelabs': '~8.4.1',
          highland: '^2.3.0',
          istanbul: '^0.3.5',
          jshint: '^2.6.0',
          'jshint-stylish': '~0.2.0',
          mkdirp: '~0.5.0',
          mocha: '~2.1',
          open: '~0.0.5',
          optimist: '~0.6.1',
          rimraf: '~2.2.6',
          rx: '^2.3.25',
          'serve-static': '^1.7.1',
          sinon: '~1.7.3',
          'uglify-js': '~2.4.16',
          kefir: '^2.4.1' },
       main: './js/release/bluebird.js',
       browser: './js/browser/bluebird.js',
       files: [ 'js/browser', 'js/release', 'LICENSE' ],
       gitHead: '621a8785d81d039241bbce19e6db495d0973aa45',
       _id: 'bluebird@3.1.5',
       _shasum: '69278a1e1d365a1817ba88f3214c2f942779d0ae',
       _from: 'bluebird@latest',
       _npmVersion: '3.3.12',
       _nodeVersion: '5.2.0',
       _npmUser: { name: 'esailija', email: 'petka_antonov@hotmail.com' },
       dist:
        { shasum: '69278a1e1d365a1817ba88f3214c2f942779d0ae',
          tarball: 'http://registry.npmjs.org/bluebird/-/bluebird-3.1.5.tgz' },
       maintainers: [ { name: 'esailija', email: 'petka_antonov@hotmail.com' } ],
       directories: {},
       _resolved: 'https://registry.npmjs.org/bluebird/-/bluebird-3.1.5.tgz',
       readme: 'ERROR: No README data found!',
       realName: 'bluebird',
       dependencies: {},
       _dependencies: {},
       extraneous: false,
       path: '/Users/samrichard/Development/plugabilly/node_modules/bluebird',
       realPath: '/Users/samrichard/Development/plugabilly/node_modules/bluebird',
       parent: '[Circular]',
       depth: 1,
       peerDependencies: {} } },
  { path: '/Users/samrichard/Development/plugabilly/node_modules/coveralls',
    package:
     { name: 'coveralls',
       description: 'takes json-cov output into stdin and POSTs to coveralls.io',
       keywords: [ 'coverage', 'coveralls' ],
       version: '2.11.6',
       bugs: { url: 'https://github.com/nickmerwin/node-coveralls/issues' },
       scripts: { test: 'make test' },
       bin: { coveralls: './bin/coveralls.js' },
       maintainers:
        [ { name: 'cainus', email: 'gregg@caines.ca' },
          { name: 'nickmerwin', email: 'n@mer.fm' } ],
       contributors:
        [ { name: 'Gregg Caines',
            email: 'gregg@caines.ca',
            url: 'http://caines.ca' },
          { name: 'Joshua Ma',
            email: 'github@joshma.com',
            url: 'http://joshma.com' },
          { name: 'Alan Gutierrez',
            email: 'alan@prettyrobots.com',
            url: 'http://www.prettyrobots.com/' },
          { name: 'Kir Belevich', url: 'https://github.com/svg' },
          { name: 'elliotcable',
            email: 'github@elliottcable.name',
            url: 'http://elliottcable.name/' },
          { name: 'Slotos',
            email: 'slotos@gmail.com',
            url: 'http://slotos.net' },
          { name: 'mattjmorrison',
            email: 'mattjmorrison@mattjmorrison.com',
            url: 'http://mattjmorrison.com' },
          { name: 'Arpad Borsos',
            email: 'arpad.borsos@googlemail.com',
            url: 'http://swatinem.de/' } ],
       dependencies: { coveralls: { dependencies: {} } },
       devDependencies:
        { 'sinon-restore': '1.0.0',
          'mocha-lcov-reporter': '0.0.1',
          mocha: '1.8.1',
          should: '1.1.0',
          istanbul: '0.2.10',
          jshint: '2.1.3' },
       engines: { node: '>=0.8.6' },
       main: 'index.js',
       directories: { test: 'test' },
       repository:
        { type: 'git',
          url: 'git://github.com/nickmerwin/node-coveralls.git' },
       author: { name: 'Gregg Caines' },
       license: 'BSD-2-Clause',
       gitHead: '8c06415c4dfbd72043f26afdf7e34313d5c4444d',
       homepage: 'https://github.com/nickmerwin/node-coveralls#readme',
       _id: 'coveralls@2.11.6',
       _shasum: '7854ae74b19e2c5bcdae9955b6cd5fb83c0d4ba6',
       _from: 'coveralls@>=2.11.6 <3.0.0',
       _npmVersion: '2.12.1',
       _nodeVersion: '0.12.7',
       _npmUser: { name: 'nickmerwin', email: 'n@mer.fm' },
       dist:
        { shasum: '7854ae74b19e2c5bcdae9955b6cd5fb83c0d4ba6',
          tarball: 'http://registry.npmjs.org/coveralls/-/coveralls-2.11.6.tgz' },
       _resolved: 'https://registry.npmjs.org/coveralls/-/coveralls-2.11.6.tgz',
       readme: 'ERROR: No README data found!',
       realName: 'coveralls',
       _dependencies:
        { 'js-yaml': '3.0.1',
          'lcov-parse': '0.0.6',
          'log-driver': '1.2.4',
          request: '2.67.0',
          minimist: '1.2.0' },
       extraneous: false,
       path: '/Users/samrichard/Development/plugabilly/node_modules/coveralls',
       realPath: '/Users/samrichard/Development/plugabilly/node_modules/coveralls',
       parent: '[Circular]',
       depth: 1,
       peerDependencies: {} } },
  { path: '/Users/samrichard/Development/plugabilly/node_modules/eslint',
    package:
     { name: 'eslint',
       version: '1.10.3',
       author:
        { name: 'Nicholas C. Zakas',
          email: 'nicholas+npm@nczconsulting.com' },
       description: 'An AST-based pattern checker for JavaScript.',
       bin: { eslint: './bin/eslint.js' },
       main: './lib/api.js',
       scripts:
        { test: 'node Makefile.js test',
          lint: 'node Makefile.js lint',
          patch: 'node Makefile.js patch',
          minor: 'node Makefile.js minor',
          major: 'node Makefile.js major',
          docs: 'node Makefile.js docs',
          gensite: 'node Makefile.js gensite',
          browserify: 'node Makefile.js browserify',
          perf: 'node Makefile.js perf',
          profile: 'beefy tests/bench/bench.js --open -- -t brfs -t ./tests/bench/xform-rules.js -r espree',
          coveralls: 'cat ./coverage/lcov.info | coveralls',
          'check-commit': 'node Makefile.js checkGitCommit' },
       files: [ 'LICENSE', 'README.md', 'bin', 'conf', 'lib' ],
       repository: { type: 'git', url: 'git+https://github.com/eslint/eslint.git' },
       homepage: 'http://eslint.org',
       bugs: { url: 'https://github.com/eslint/eslint/issues/' },
       dependencies: { eslint: { dependencies: {} } },
       devDependencies:
        { beefy: '^1.0.0',
          brfs: '0.0.9',
          browserify: '^12.0.1',
          chai: '^3.4.0',
          cheerio: '^0.19.0',
          coveralls: '2.11.4',
          dateformat: '^1.0.8',
          ejs: '^2.3.3',
          esprima: '^2.4.1',
          'esprima-fb': '^15001.1001.0-dev-harmony-fb',
          'gh-got': '^2.2.0',
          istanbul: '^0.4.0',
          jsdoc: '^3.3.0-beta1',
          jsonlint: '^1.6.2',
          leche: '^2.1.1',
          linefix: '^0.1.1',
          'load-perf': '^0.2.0',
          markdownlint: '^0.0.8',
          mocha: '^2.1.0',
          'mocha-phantomjs': '4.0.1',
          'npm-license': '^0.3.1',
          phantomjs: '1.9.18',
          proxyquire: '^1.0.0',
          rewire: '^2.3.4',
          semver: '^5.0.3',
          'shelljs-nodecli': '~0.1.0',
          sinon: '1.17.2',
          through: '^2.3.6' },
       keywords: [ 'ast', 'lint', 'javascript', 'ecmascript', 'espree' ],
       license: 'MIT',
       engines: { node: '>=0.10' },
       gitHead: '2436cc6c1816a7890e35dab38e609daee84d7530',
       _id: 'eslint@1.10.3',
       _shasum: 'fb19a91b13c158082bbca294b17d979bc8353a0a',
       _from: 'eslint@>=1.10.3 <2.0.0',
       _npmVersion: '1.4.28',
       _npmUser: { name: 'nzakas', email: 'nicholas@nczconsulting.com' },
       maintainers:
        [ { name: 'nzakas', email: 'nicholas@nczconsulting.com' },
          { name: 'ivolodin', email: 'ivolodin@gmail.com' } ],
       dist:
        { shasum: 'fb19a91b13c158082bbca294b17d979bc8353a0a',
          tarball: 'http://registry.npmjs.org/eslint/-/eslint-1.10.3.tgz' },
       directories: {},
       _resolved: 'https://registry.npmjs.org/eslint/-/eslint-1.10.3.tgz',
       readme: 'ERROR: No README data found!',
       realName: 'eslint',
       _dependencies:
        { chalk: '^1.0.0',
          'concat-stream': '^1.4.6',
          debug: '^2.1.1',
          doctrine: '^0.7.1',
          'escape-string-regexp': '^1.0.2',
          escope: '^3.3.0',
          espree: '^2.2.4',
          estraverse: '^4.1.1',
          'estraverse-fb': '^1.3.1',
          esutils: '^2.0.2',
          'file-entry-cache': '^1.1.1',
          glob: '^5.0.14',
          globals: '^8.11.0',
          handlebars: '^4.0.0',
          inquirer: '^0.11.0',
          'is-my-json-valid': '^2.10.0',
          'is-resolvable': '^1.0.0',
          'js-yaml': '3.4.5',
          'json-stable-stringify': '^1.0.0',
          'lodash.clonedeep': '^3.0.1',
          'lodash.merge': '^3.3.2',
          'lodash.omit': '^3.1.0',
          minimatch: '^3.0.0',
          mkdirp: '^0.5.0',
          'object-assign': '^4.0.1',
          optionator: '^0.6.0',
          'path-is-absolute': '^1.0.0',
          'path-is-inside': '^1.0.1',
          shelljs: '^0.5.3',
          'strip-json-comments': '~1.0.1',
          'text-table': '~0.2.0',
          'user-home': '^2.0.0',
          'xml-escape': '~1.0.0' },
       extraneous: false,
       path: '/Users/samrichard/Development/plugabilly/node_modules/eslint',
       realPath: '/Users/samrichard/Development/plugabilly/node_modules/eslint',
       parent: '[Circular]',
       depth: 1,
       peerDependencies: {} } },
  { path: '/Users/samrichard/Development/plugabilly/node_modules/jsdoc',
    package:
     { name: 'jsdoc',
       version: '3.4.0',
       revision: '1447115289326',
       description: 'An API documentation generator for JavaScript.',
       keywords: [ 'documentation', 'javascript' ],
       license: 'Apache-2.0',
       repository: { type: 'git', url: 'git+https://github.com/jsdoc3/jsdoc.git' },
       dependencies: { jsdoc: { dependencies: {} } },
       devDependencies:
        { gulp: '~3.9.0',
          'gulp-eslint': '~1.0.0',
          'gulp-json-editor': '~2.2.1',
          istanbul: '~0.3.17',
          tv4: 'https://github.com/hegemonic/tv4/tarball/own-properties' },
       engines: { node: '>=0.10' },
       scripts: { test: 'gulp lint; gulp test' },
       bin: { jsdoc: './jsdoc.js' },
       bugs: { url: 'https://github.com/jsdoc3/jsdoc/issues' },
       author: { name: 'Michael Mathews', email: 'micmath@gmail.com' },
       contributors: [ { url: 'https://github.com/jsdoc3/jsdoc/graphs/contributors' } ],
       maintainers:
        [ { name: 'kzh', email: 'kaleb@hornsby.ws' },
          { name: 'hegemonic', email: 'jeffrey.l.williams@gmail.com' } ],
       gitHead: '62b5dbe0c7519d9126f528436b3b77350698f74b',
       homepage: 'https://github.com/jsdoc3/jsdoc#readme',
       _id: 'jsdoc@3.4.0',
       _shasum: '341cdb06e44a113d9541efd212c95a488064e9ee',
       _from: 'jsdoc@>=3.4.0 <4.0.0',
       _npmVersion: '2.14.7',
       _nodeVersion: '4.2.0',
       _npmUser: { name: 'hegemonic', email: 'jeffrey.l.williams@gmail.com' },
       dist:
        { shasum: '341cdb06e44a113d9541efd212c95a488064e9ee',
          tarball: 'http://registry.npmjs.org/jsdoc/-/jsdoc-3.4.0.tgz' },
       directories: {},
       _resolved: 'https://registry.npmjs.org/jsdoc/-/jsdoc-3.4.0.tgz',
       readme: 'ERROR: No README data found!',
       realName: 'jsdoc',
       _dependencies:
        { async: '~1.4.0',
          bluebird: '~2.9.34',
          catharsis: '~0.8.7',
          'escape-string-regexp': '~1.0.3',
          espree: '~2.2.3',
          js2xmlparser: '~1.0.0',
          marked: '~0.3.4',
          requizzle: '~0.2.0',
          'strip-json-comments': '~1.0.2',
          taffydb: 'https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e',
          underscore: '~1.8.3',
          wrench: '~1.5.8' },
       extraneous: false,
       path: '/Users/samrichard/Development/plugabilly/node_modules/jsdoc',
       realPath: '/Users/samrichard/Development/plugabilly/node_modules/jsdoc',
       parent: '[Circular]',
       depth: 1,
       peerDependencies: {} } },
  { path: '/Users/samrichard/Development/plugabilly/node_modules/eslint-config-xo-space',
    package:
     { name: 'eslint-config-xo-space',
       version: '0.8.0',
       description: 'ESLint shareable config for XO with 2-space indent',
       license: 'MIT',
       repository:
        { type: 'git',
          url: 'git+https://github.com/sindresorhus/eslint-config-xo-space.git' },
       author:
        { name: 'Sindre Sorhus',
          email: 'sindresorhus@gmail.com',
          url: 'sindresorhus.com' },
       engines: { node: '>=0.10.0' },
       scripts: { test: 'ava' },
       files: [ 'index.js', 'esnext.js', 'browser.js' ],
       keywords:
        [ '❤️',
          'space',
          'spaces',
          'eslintconfig',
          'xo',
          'xoxo',
          'hugs',
          'kisses',
          'happy',
          'happiness',
          'code',
          'quality',
          'style',
          'lint',
          'linter',
          'jscs',
          'jshint',
          'jslint',
          'eslint',
          'validate',
          'code style',
          'standard',
          'strict',
          'check',
          'checker',
          'verify',
          'enforce',
          'hint',
          'simple' ],
       dependencies: { 'eslint-config-xo-space': { dependencies: {} } },
       devDependencies:
        { ava: '*',
          'babel-eslint': '^4.1.1',
          'clear-require': '^1.0.1',
          eslint: '^1.9.0',
          'eslint-plugin-babel': '^3.0.0',
          'is-plain-obj': '^1.0.0',
          'temp-write': '^2.0.1' },
       peerDependencies: { eslint: '>=1.9.0' },
       gitHead: '05bc3d7019c432ea375f8791a79a796cdf4ad023',
       bugs: { url: 'https://github.com/sindresorhus/eslint-config-xo-space/issues' },
       homepage: 'https://github.com/sindresorhus/eslint-config-xo-space',
       _id: 'eslint-config-xo-space@0.8.0',
       _shasum: 'dec5a37fd55ba351b57cdd3f5bc1ac731b4dbd13',
       _from: 'eslint-config-xo-space@>=0.8.0 <0.9.0',
       _npmVersion: '2.14.7',
       _nodeVersion: '4.2.1',
       _npmUser: { name: 'sindresorhus', email: 'sindresorhus@gmail.com' },
       dist:
        { shasum: 'dec5a37fd55ba351b57cdd3f5bc1ac731b4dbd13',
          tarball: 'http://registry.npmjs.org/eslint-config-xo-space/-/eslint-config-xo-space-0.8.0.tgz' },
       maintainers: [ { name: 'sindresorhus', email: 'sindresorhus@gmail.com' } ],
       directories: {},
       _resolved: 'https://registry.npmjs.org/eslint-config-xo-space/-/eslint-config-xo-space-0.8.0.tgz',
       readme: 'ERROR: No README data found!',
       realName: 'eslint-config-xo-space',
       _dependencies:
        { 'deep-assign': '^2.0.0',
          'eslint-config-xo': '^0.9.0',
          eslint: '>=1.9.0' },
       extraneous: false,
       path: '/Users/samrichard/Development/plugabilly/node_modules/eslint-config-xo-space',
       realPath: '/Users/samrichard/Development/plugabilly/node_modules/eslint-config-xo-space',
       parent: '[Circular]',
       depth: 1 } },
  { path: '/Users/samrichard/Development/plugabilly/node_modules/nyc',
    package:
     { name: 'nyc',
       version: '5.5.0',
       description: 'a code coverage tool that works well with subprocesses.',
       main: 'index.js',
       scripts:
        { pretest: 'standard',
          test: 'npm run cover',
          clean: 'rimraf ./.nyc_output ./node_modules/.cache ./.self_coverage ./test/fixtures/.nyc_output ./test/fixtures/node_modules/.cache *covered.js ./lib/*covered.js',
          build: 'node ./build-tests',
          instrument: 'node ./build-self-coverage.js',
          'run-tests': 'tap --no-cov -b ./test/build/*.js ./test/src/source-map-cache.js',
          report: 'istanbul report --include=./.self_coverage/*.json lcov text',
          cover: 'npm run clean && npm run build && npm run instrument && npm run run-tests && npm run report',
          dev: 'npm run clean && npm run build && npm run run-tests' },
       bin: { nyc: './bin/nyc.js' },
       files: [ 'index.js', 'bin/*.js', 'lib/*.js', '!**/*covered.js' ],
       nyc:
        { exclude:
           [ 'node_modules',
             'bin',
             'coverage',
             'test/fixtures/coverage.js',
             'test/build/*',
             'test/nyc-test.js',
             'test/source-map-cache.js',
             'index.covered.js',
             'test/fixtures/_generateCoverage.js' ] },
       standard: { ignore: [ '**/fixtures/**', '**/test/build/*' ] },
       keywords: [ 'coverage', 'reporter', 'subprocess', 'testing' ],
       contributors: [ { name: 'Isaac Schlueter' }, { name: 'Ollie Buck' } ],
       author: { name: 'Ben Coe', email: 'ben@npmjs.com' },
       license: 'ISC',
       dependencies: { nyc: { dependencies: {} } },
       devDependencies:
        { 'any-path': '^1.3.0',
          chai: '^3.0.0',
          coveralls: '^2.11.4',
          'exists-sync': '0.0.3',
          'forking-tap': '^0.1.1',
          'is-windows': '^0.1.0',
          lodash: '^3.10.0',
          'newline-regex': '^0.2.1',
          'sanitize-filename': '^1.5.3',
          sinon: '^1.15.3',
          'source-map-fixtures': '^0.4.0',
          'source-map-support': '^0.4.0',
          'split-lines': '^1.0.0',
          standard: '^5.2.1',
          tap: '^2.3.4',
          'zero-fill': '^2.2.1' },
       repository: { type: 'git', url: 'git+ssh://git@github.com/bcoe/nyc.git' },
       gitHead: '3621913b54095eba70df7f37b79c413b58a43722',
       bugs: { url: 'https://github.com/bcoe/nyc/issues' },
       homepage: 'https://github.com/bcoe/nyc#readme',
       _id: 'nyc@5.5.0',
       _shasum: '5782ae776e11e0fad96e84978d68ecd61be3410c',
       _from: 'nyc@>=5.3.0 <6.0.0',
       _npmVersion: '3.3.0',
       _nodeVersion: '3.2.0',
       _npmUser: { name: 'bcoe', email: 'ben@npmjs.com' },
       dist:
        { shasum: '5782ae776e11e0fad96e84978d68ecd61be3410c',
          tarball: 'http://registry.npmjs.org/nyc/-/nyc-5.5.0.tgz' },
       maintainers:
        [ { name: 'bcoe', email: 'ben@npmjs.com' },
          { name: 'isaacs', email: 'isaacs@npmjs.com' } ],
       directories: {},
       _resolved: 'https://registry.npmjs.org/nyc/-/nyc-5.5.0.tgz',
       readme: 'ERROR: No README data found!',
       realName: 'nyc',
       _dependencies:
        { 'append-transform': '^0.2.0',
          arrify: '^1.0.1',
          'caching-transform': '^1.0.0',
          'convert-source-map': '^1.1.2',
          'find-cache-dir': '^0.1.1',
          'foreground-child': '^1.3.5',
          glob: '^6.0.2',
          istanbul: '^0.4.1',
          'md5-hex': '^1.2.0',
          micromatch: '~2.1.6',
          mkdirp: '^0.5.0',
          'pkg-up': '^1.0.0',
          'read-pkg': '^1.1.0',
          'resolve-from': '^2.0.0',
          rimraf: '^2.5.0',
          'signal-exit': '^2.1.1',
          'source-map': '^0.5.3',
          'spawn-wrap': '^1.1.1',
          'strip-bom': '^2.0.0',
          yargs: '^3.15.0' },
       extraneous: false,
       path: '/Users/samrichard/Development/plugabilly/node_modules/nyc',
       realPath: '/Users/samrichard/Development/plugabilly/node_modules/nyc',
       parent: '[Circular]',
       depth: 1,
       peerDependencies: {} } },
  { path: '/Users/samrichard/Development/plugabilly/node_modules/tap-diff',
    package:
     { name: 'tap-diff',
       version: '0.1.1',
       description: 'The most human-friendly TAP reporter',
       main: './distributions/index.js',
       bin: { 'tap-diff': './distributions/cli.js' },
       scripts:
        { babel: 'babel ./sources --out-dir ./distributions',
          test: 'echo "Error: no test specified" && exit 1' },
       author:
        { name: 'axross',
          email: 'kou@axross.org',
          url: 'http://axross.me/' },
       license: 'MIT',
       dependencies: { 'tap-diff': { dependencies: {} } },
       devDependencies: { babel: '^5.8.34' },
       repository:
        { type: 'git',
          url: 'git+https://github.com/axross/tap-diff.git' },
       bugs: { url: 'https://github.com/axross/tap-diff/issues' },
       homepage: 'https://github.com/axross/tap-diff#readme',
       keywords: [ 'tap', 'tape', 'ava', 'test', 'reporter', 'diff' ],
       gitHead: 'f951cf018ff5644c9812ba134f59264e49eed478',
       _id: 'tap-diff@0.1.1',
       _shasum: '8fbf3333d85643feea1bf1759b90820b04a37ddf',
       _from: 'tap-diff@>=0.1.1 <0.2.0',
       _npmVersion: '3.3.6',
       _nodeVersion: '5.0.0',
       _npmUser: { name: 'axross', email: 'kou@axross.org' },
       dist:
        { shasum: '8fbf3333d85643feea1bf1759b90820b04a37ddf',
          tarball: 'http://registry.npmjs.org/tap-diff/-/tap-diff-0.1.1.tgz' },
       maintainers: [ { name: 'axross', email: 'kou@axross.org' } ],
       directories: {},
       _resolved: 'https://registry.npmjs.org/tap-diff/-/tap-diff-0.1.1.tgz',
       readme: 'ERROR: No README data found!',
       realName: 'tap-diff',
       _dependencies:
        { chalk: '^1.1.1',
          diff: '^2.2.1',
          duplexer: '^0.1.1',
          figures: '^1.4.0',
          'pretty-ms': '^2.1.0',
          'tap-parser': '^1.2.2',
          through2: '^2.0.0' },
       extraneous: false,
       path: '/Users/samrichard/Development/plugabilly/node_modules/tap-diff',
       realPath: '/Users/samrichard/Development/plugabilly/node_modules/tap-diff',
       parent: '[Circular]',
       depth: 1,
       peerDependencies: {} } } ];
